config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :arguments
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/argument.rb
class Argument < ApplicationRecord
  validates :topic, presence: true,
                    length: { minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/arguments_controller.rb
class ArgumentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @arguments = Argument.all
  end

  def show
    @argument = Argument.find(params[:id])
  end

  def new
    @argument = Argument.new
  end

  def edit
    @argument = Argument.find(params[:id])
  end

  def create
    @argument = Argument.new(argument_params)
    if @argument.save
      redirect_to @argument
    else
      render 'new'
    end
  end

  def update
    @argument = Argument.find(params[:id])
    if @argument.update(argument_params)
      redirect_to @argument
    else
      render 'edit'
    end
  end

  def destroy
    @argument = Argument.find(params[:id])
    @argument.destroy
    redirect_to arguments_path
  end

  private
    def argument_params
      params.require(:argument).permit(:topic, :with_who, :outcome)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arguments_helper.rb
module ArgumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/arguments/_form.html.erb
<%= form_for @argument do |f| %>
<% if @argument.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@argument.errors.count, "error") %> prohibited
        this argument from being saved:
      </h2>
      <ul>
        <% @argument.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <%= f.label :topic %><br>
  <%= f.text_field :topic %>
</p>
<p>
  <%= f.label :with_who %><br>
  <%= f.text_field :with_who %>
</p>
<p class="range-field">
  <%= f.label :outcome %><br>
  <%= f.range_field :outcome, in: 0..100 %>
</p>
<%= f.submit "Submit", class: 'btn waves-effect waves-light' %>
<%= link_to 'Back', arguments_path, class: 'btn waves-effect waves-light grey darken-3' %>
<% end  %>

app/views/arguments/edit.html.erb
<h2>Edit Argument</h2>
<%= render 'form' %>

app/views/arguments/index.html.erb
<h2>You argue a lot</h2>

<table class="responsive-table striped">
  <thead>
    <tr>
      <th>Topic</th>
      <th>With Who</th>
      <th>Outcome</th>
    </tr>
  </thead>
  <tbody>
  <% @arguments.each do |argument| %>
    <tr>
      <td><%= link_to argument.topic, argument_path(argument) %></td>
      <td><%= argument.with_who %></td>
      <td><%= argument.outcome %></td>
      <td><%= link_to 'Edit', edit_argument_path(argument), class: 'btn waves-effect waves-light green' %></td>
      <td><%= link_to 'Destroy', argument_path(argument),
              method: :delete,
              data: { confirm: 'for reals?' }, class: 'btn waves-effect waves-light red' %></td>
  <% end %>
  </tbody>
</table>
<p>
  <%= link_to 'New Argument', new_argument_path, class: 'btn waves-effect waves-light' %>
</p>

app/views/arguments/new.html.erb
<h2>New Argument</h2>
<%= render 'form' %>

app/views/arguments/show.html.erb
<p>
  <strong>Topic:</strong>
  <%= @argument.topic %>
</p>
<p>
  <strong>With who:</strong>
  <%= @argument.with_who %>
</p>
<p>
  <strong>Outcome:</strong>
  <%= @argument.outcome %>
</p>


<p>
  <%= link_to 'Back', arguments_path %>
</p>

app/views/home/index.html.erb
<h1>Am I Right???</h1>
<%= link_to 'Were you right?', arguments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amiright</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>